server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: kuberez
          uri: http://localhost:8081
          predicates:
            - Path=/dash/**,/static/**,/app.js,/manifest.json,/img/**
        - id: webkubectl
          uri: http://localhost:8082
          predicates:
            - Path=/api/**,/terminal/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


